const defaultTasks = [
	{
		id: 1,
		name: "brush your teeth AM",
		points: 10,
		complete: false,
		repeat: true,
		repeatFrequency: "daily",
	},
	{
		id: 2,
		name: "brush your teeth PM",
		points: 10,
		complete: false,
		repeat: true,
		repeatFrequency: "daily",
	},
	{
		id: 3,
		name: "make the bed",
		points: 10,
		complete: false,
		repeat: true,
		repeatFrequency: "daily",
	},
	{
		id: 4,
		name: "read for 10 mins",
		points: 10,
		complete: false,
		repeat: true,
		repeatFrequency: "daily",
	},
	{
		id: 5,
		name: "exercise for 30 mins",
		points: 20,
		complete: false,
		repeat: true,
		repeatFrequency: "daily",
	},
	{
		id: 6,
		name: "go on a walk",
		points: 10,
		complete: false,
		repeat: true,
		repeatFrequency: "daily",
	},
	{
		id: 7,
		name: "write in a journal",
		points: 10,
		complete: false,
		repeat: true,
		repeatFrequency: "daily",
	},
	{
		id: 8,
		name: "do the laundry",
		points: 30,
		complete: false,
		repeat: true,
		repeatFrequency: "weekly",
	},
	{
		id: 9,
		name: "check your budget",
		points: 25,
		complete: false,
		repeat: true,
		repeatFrequency: "monthly",
	},
];

export { defaultTasks };
